### ISSUE TITLE
Unable to get property 'focus' of undefined or null reference

### ISSUE THREAD

**Issue by hfishere** [pnmcosta/jquery-socialshare#2]
Hei, i like your plugin and i used it for my job..
But i've got an issue when im download the plugin and run index.html in Edge, something happened like this.

![image](https://cloud.githubusercontent.com/assets/13634344/25078822/eb9a1570-2360-11e7-8c56-8bac32a1180a.png)

and the popup wont show but open new window on browser..
But your code works well at this demo (http://www.jqueryscript.net/demo/Custom-Social-Share-Buttons-Links-With-jQuery-socialShare/) even in Edge browser..
Am i do something wrong?
Thanks..

**Comment by pnmcosta** [comment]
Hi @hfishere 

Glad you like the plugin, and are using it, let me know if it ever goes into production :)

If you've opened it from a local version of index.html on edge, e.g. "file://...", it's likely that is the problem, running from file:// is not really supported nor the intended goal of the plugin.

Please note that I think that the link you supplied download version may be outdated, it's now on v1.0.3, see #1 for more info and always download from the Releases tab above.

Thanks,
P.
